language: python
python:
- '3.6'
services:
- docker
script:
- "./test.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_238944315dda_key -iv $encrypted_238944315dda_iv -in deployer.enc -out deployer -d
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy; fi
