language: python
python:
- '3.6'
services:
- docker
script:
- "./test.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_238944315dda_key -iv $encrypted_238944315dda_iv -in deployer.enc -out deployer -d
- set -e; chmod 600 deploy; eval `ssh-agent -s`; ssh-add deployer;
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  set -e;
  wget https://gist.githubusercontent.com/OmegaDroid/22b6e15b2050841d5733095509a97258/raw/e1c8cf52ee3e139c06fa5ac81e4a326621fdd20e/up_version.py;
  chmod +x up_version.py;
  git config --global user.email "deployer@wildfish.com";
  git config --global user.name "WildfishDeployer";
  TAG=`./up_version.py`;
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  ./push.sh $TAG;
  fi
