language: python
python:
- '3.6'
services:
- docker
script:
- "./test.sh"
before_deploy:
- openssl aes-256-cbc -K $encrypted_238944315dda_key -iv $encrypted_238944315dda_iv -in .travis/deployer.enc -out /tmp/deployer -d
- chmod 600 /tmp/deployer;
- eval `ssh-agent -s`;
- ssh-add /tmp/deployer;
deploy:
- provider: script
  skip_cleanup: true
  script: ./.travis/deploy.sh
  on:
    branch: master
